### ISSUE TITLE
Instagram Embed

### ISSUE THREAD

**Issue by greeenboi** [founder-srm/Camber-monorepo#7]
Create a scrollable(sideways) component to display content from their instagram .

You are free to design and implement how this particular component would work.

Refer to the attached image for an idea 

<sub><a href="https://huly.app/guest/founderstechnical?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmVhYzg5MTQ5YzY4N2Y5NWNmMWNkZTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZ3JlZWVuLWZvdW5kZXJzdGVjaC02NmFlNzdiYy01ZmUxN2YzMTYzLTJhNzUzZSJ9.HyO-YfJQDSqTxkhuU-h7eykkjJWkvfTBYZuI8f98R40">Huly&reg;: <b>CAMBE-3</b></a></sub>

**Comment by greeenboi** [comment]
There seems to be a hydration error on the website, check whats up with that? @SaranshBangar

**Comment by SaranshBangar** [comment]
![image](https://github.com/user-attachments/assets/634a23b4-8cae-424f-b0ff-7f7390a4dd07)

That is because insta takes some time to render the embedded posts, I am not sure to deal with it

![image](https://github.com/user-attachments/assets/cf8926ca-4b17-4cec-b5df-5e98983cc20f)

There is no hydration after the posts are rendered

**Comment by greeenboi** [comment]
@SaranshBangar  use the `<suspense></suspense>` tag to wrap the embed frame
